name: a_star
version: 0.3.0
author: Seth Ladd <sethladd@gmail.com>
description: A sample A* algorithm built with Dart.
homepage: https://github.com/sethladd/dart-a-star
dependencies:
  collection: any
dev_dependencies:
  benchmark_harness: any
  browser: any
  unittest: any
